# .travis.yml
language: ruby
cache:
  bundler: true
  apt: true
services:
  - redis-server
rvm:
  - 2.3.0
before_install:
  - gem update --system
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get install -y sphinxsearch
script:
  - RAILS_ENV=test bin/rake db:drop db:create db:schema:load
  - cp config/initializers/localeapp.rb.travis config/initializers/localeapp.rb
  - RAILS_ENV=test bin/rake ts:configure
  - RAILS_ENV=test bin/rake ts:index
  - RAILS_ENV=test bin/rake ts:start
  - bin/rake nolotiro:download_maxmind_db
  - bin/rake test
before_script:
  - mysql -e 'create database nolotirov3_test;'
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.yml.travis config/database.yml
branches:
  only:
    - master
env:
  - DATABASE=mysql2 SPHINX_BIN=/usr/bin/ SPHINX_VERSION=2.0.4
