---

# Configuration

branches:
  only:
    - master

cache:
  bundler: true

env:
  - NLT_DB_USER=travis NLT_DB_PASS=''

language: ruby

rvm:
  - 2.3.1

services:
  - redis-server

# Phases

before_install:
  - gem update --system
  - gem install bundler
  - source bin/phantomjs.sh

script:
  - RAILS_ENV=test bin/rake db:drop db:create db:structure:load max_mind:extract
  - bin/rake test rubocop

before_deploy:
  - openssl aes-256-cbc -K $encrypted_5358ea3d75c2_key
    -iv $encrypted_5358ea3d75c2_iv -in config/deploy/rsa_key.enc
    -out config/deploy/rsa_key -d

deploy:
  provider: script
  script: rvm $TRAVIS_RUBY_VERSION do bin/cap production deploy
  skip_cleanup: true
  on:
    branch: master
